const dati = [
  {
    nome: "Jimmy",
    cognome: "Saavedra",
    età: 30,
    città: "Genova",
    hobby: "Trading",
    ciboPreferito: "Encebollado",
    videogiocoPreferito: "LOL",
    filmPreferito: "Resident Evil",
    libroPreferito: "Asesino Accidental",
    nomeAnimaleDomestico: "Saoko",
  },
  {
    nome: "Francesca",
    cognome: "Pischedda",
    età: 32,
    città: "Cagliari",
    hobby: "Cucinare",
    ciboPreferito: "Pizza",
    videogiocoPreferito: " ",
    filmPreferito: "Pretty Woman",
    libroPreferito: "Succede sempre qualcosa di meraviglioso",
    nomeAnimaleDomestico: "Peggy",
  },
];
